name: multicast_lock
description: A new flutter plugin project.
version: 0.0.7
author: Stanislav Humplík <sh@analogic.cz>
homepage: https://github.com/analogic/multicast_lock

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: cz.analogic.multicastlock
    pluginClass: MulticastLockPlugin
